#!/bin/bash
#
# A simple framework for testing the bn scripts
#
# Returns the number of failed test cases.
#
# Format of a test:
#     test 'command' expected_return_value 'stdin text' 'expected stdout' 'expected stder

##########################################
# EXAMPLE TEST CASES
##########################################

# simple success
test './bn 2022 m' 0 'Sam' '2022: Sam ranked 658 out of 14255 male names.' ''

# multi line success
test './bn 2022 B' 0 'Sam' '2022: Sam ranked 658 out of 14255 male names.
2022: Sam ranked 6628 out of 17660 female names.' ''

# error case
test './bn 2022 F' 3 'Sam2' '' 'Badly formatted name: Sam2'  

# multi line error case #2
test './bn 1111 X' 2 '' '' 'Badly formatted assigned gender: X
bn <year> <assigned gender: f|F|m|M|b|B>'

# return code
exit $fails
